/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 toyota_gt-86.glb 
Author: Car2022 (https://sketchfab.com/Car2022)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toyota-gt-86-27a7c524abec49059f9542a0a04ffad9
Title: Toyota GT-86
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ToyotaGT86(props) {
  const { nodes, materials } = useGLTF("/models/toyota_gt-86.glb")
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh geometry={nodes.Material2.geometry} material={materials.reflector} />
        <mesh geometry={nodes.Material3.geometry} material={materials.tail_light} />
        <mesh geometry={nodes.Material3_1.geometry} material={materials.textured_reflect} />
        <mesh geometry={nodes.Material3_2.geometry} material={materials.plastic2} />
        <mesh geometry={nodes.Material2_1.geometry} material={materials.black1} />
        <mesh geometry={nodes.Material2_2.geometry} material={materials.black1} />
        <lineSegments geometry={nodes.Material4.geometry} material={materials.edge_color000255} />
        <mesh geometry={nodes.Material2_3.geometry} material={materials.material} />
        <lineSegments geometry={nodes.Material3_3.geometry} material={materials.edge_color353232255} />
        <mesh geometry={nodes.Material2_4.geometry} material={materials.Color_B01_3} />
        <lineSegments geometry={nodes.Material5.geometry} material={materials.edge_color736968255} />
        <mesh geometry={nodes.Material3_4.geometry} material={materials.Color_B01_4} />
        <mesh geometry={nodes.Material2_5.geometry} material={materials.Color_A03_1} />
        <mesh geometry={nodes.Material3_5.geometry} material={materials.black} />
        <lineSegments geometry={nodes.Material4_1.geometry} material={materials.edge_color353535255} />
        <lineSegments geometry={nodes.Material4_2.geometry} material={materials.edge_color454545255} />
        <mesh geometry={nodes.Material2_6.geometry} material={materials.wheel1} />
        <lineSegments geometry={nodes.Material3_6.geometry} material={materials.edge_color404040255} />
        <mesh geometry={nodes.Material2_7.geometry} material={materials.tires} />
        <mesh geometry={nodes.Material3_7.geometry} material={materials.Color_A08} />
        <lineSegments geometry={nodes.Material3_8.geometry} material={materials.edge_color121212115} />
        <mesh geometry={nodes.Material2_8.geometry} material={materials.material_20} />
        <mesh geometry={nodes.Material2_9.geometry} material={materials.material_21} />
        <lineSegments geometry={nodes.Material3_9.geometry} material={materials.edge_color252525255} />
        <lineSegments geometry={nodes.Material3_10.geometry} material={materials.edge_color63636382} />
        <mesh geometry={nodes.Material2_10.geometry} material={materials.material_24} />
        <mesh geometry={nodes.Material2_11.geometry} material={materials.Color_B06} />
        <lineSegments geometry={nodes.Material3_11.geometry} material={materials.edge_color22222228} />
        <lineSegments geometry={nodes.Material3_12.geometry} material={materials.edge_color122122122255} />
        <mesh geometry={nodes.Material2_12.geometry} material={materials.Color_B06_1} />
        <mesh geometry={nodes.Material3_13.geometry} material={materials.body} />
        <mesh geometry={nodes.Material2_13.geometry} material={materials.Color_B07} />
        <lineSegments geometry={nodes.Material3_14.geometry} material={materials.edge_color224224224255} />
        <lineSegments geometry={nodes.Material3_15.geometry} material={materials.edge_color237239242255} />
        <mesh geometry={nodes.Material3_16.geometry} material={materials.chrome} />
        <lineSegments geometry={nodes.Material5_1.geometry} material={materials.edge_color193193193255} />
        <mesh geometry={nodes.Material2_14.geometry} material={materials.Color_A02} />
        <mesh geometry={nodes.Material2_15.geometry} material={materials.Color_A05} />
        <mesh geometry={nodes.Material3_17.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Material3_18.geometry} material={materials.material_0} />
        <lineSegments geometry={nodes.Material5_2.geometry} material={materials.edge_color197197197255} />
        <lineSegments geometry={nodes.Material3_19.geometry} material={materials.edge_color16516516579} />
        <mesh geometry={nodes.Material2_16.geometry} material={materials.Color_B01_1} />
        <lineSegments geometry={nodes.Material3_20.geometry} material={materials.edge_color1750079} />
        <mesh geometry={nodes.Material2_17.geometry} material={materials.Color_B01_2} />
        <lineSegments geometry={nodes.Material5_3.geometry} material={materials.edge_color182183186255} />
        <mesh geometry={nodes.Material3_21.geometry} material={materials.Color_A03} />
        <mesh geometry={nodes.Material3_22.geometry} material={materials.Color_B01_5} />
        <lineSegments geometry={nodes.Material4_3.geometry} material={materials.edge_color109109109255} />
        <mesh geometry={nodes.Material3_23.geometry} material={materials.mirror} />
        <mesh geometry={nodes.Material3_24.geometry} material={materials.Color_B06_3} />
        <lineSegments geometry={nodes.Material4_4.geometry} material={materials.edge_color17500255} />
        <mesh geometry={nodes.Material2_18.geometry} material={materials.Color_B01} />
        <lineSegments geometry={nodes.Material4_5.geometry} material={materials.edge_color206206206255} />
        <mesh geometry={nodes.Material3_25.geometry} material={materials.material_55} />
        <mesh geometry={nodes.Material3_26.geometry} material={materials.Color_A08_2} />
        <lineSegments geometry={nodes.Material5_4.geometry} material={materials.edge_color151515255} />
        <mesh geometry={nodes.Material3_27.geometry} material={materials.Color_A08_5} />
        <mesh geometry={nodes.Material3_28.geometry} material={materials.Color_A09} />
        <mesh geometry={nodes.Material3_29.geometry} material={materials.material_60} />
        <mesh geometry={nodes.Material3_30.geometry} material={materials.material_61} />
        <mesh geometry={nodes.Material2_19.geometry} material={materials.Color_A03_2} />
        <lineSegments geometry={nodes.Material2_20.geometry} material={materials.edge_color303030255} />
        <lineSegments geometry={nodes.Material3_31.geometry} material={materials.edge_color303030255} />
        <lineSegments geometry={nodes.Material3_32.geometry} material={materials.edge_color178178178255} />
      </group>
    </group>
  )
}

useGLTF.preload("/models/toyota_gt-86.glb")
