/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Kawasaki_zx-6r.glb 
Author: valvetin (https://sketchfab.com/valvetin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kawasaki-ninja-zx-6r-4af2b6840b8045a5af5e8df8a85f04fa
Title: Kawasaki ninja ZX-6R
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Zx6r(props) {
  const { nodes, materials } = useGLTF('/models/kawasaki_zx-6r.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.45}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.Front_Wheel_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Windshield_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Front_Transmission_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Steerting_Wheel_Main_Cyl_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Sterring_Wheel_Holder_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Front_Lights_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Headlight_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Headlight_Cover_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Headlight_Inside_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Radiator_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Lights_at_front_or_whatever_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Dashboard_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Inside_Panel_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Steering_Wheel_Plate_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Button_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Sterring_Wheel_Holder001_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Dashboard_Holder_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Tank_Head_Screw_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Filter_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Taillight_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Taillight_Cover_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Exhaust_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Wharever_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Pillar_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Plane001_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Umm_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Sum_thing_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Holder_of_the_thing_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Anotha_Thing_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Holder_of_holder_of_holder_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.NurbsPath_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Plane002_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Man_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Pedal?_Mesh_0'].geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Aaaaaa_Thing_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Leg_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Front_Rim_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Brakes_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Brakes_Too_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Rear_Wheel_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Rear_Rim_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Rear_Brakes_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Rear_Brakes_Too_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Rear_Main_Brakes_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Chain_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Front_Wheel_Holder_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Key_Hole_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Steering_Wheel_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Cup?_Mesh_0'].geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Brake_Wires_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Side_Mirror_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Brake_Pads_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Brake_Holder?_Mesh_0'].geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube001_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinders_Mesh_0.geometry} material={materials.Mesh} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Shaft_Bay_or_whatever_Engine_0.geometry} material={materials.Engine} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Exhaust_from_engine_Engine_0.geometry} material={materials.Engine} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Idk_some_Tube_Engine_0.geometry} material={materials.Engine} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Shaft_Engine_0.geometry} material={materials.Engine} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Oil_Tank_Engine_0.geometry} material={materials.Engine} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Oil_Filter_Engine_0.geometry} material={materials.Engine} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Damn_theres_a_lot_of_cylinders_Engine_0.geometry} material={materials.Engine} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Something_from_engine_Engine_0.geometry} material={materials.Engine} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Engine_extension_Engine_0.geometry} material={materials.Engine} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cat_Engine_0.geometry} material={materials.Engine} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Another_Oil_Tank_lol_Engine_0.geometry} material={materials.Engine} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Fan_Engine_0.geometry} material={materials.Engine} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder014_Engine_0.geometry} material={materials.Engine} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Tank_Panels_0.geometry} material={materials.Panels} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Seat_Panels_0.geometry} material={materials.Panels} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Side_Panel_Panels_0.geometry} material={materials.Panels} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Front_Side_Panel_Panels_0.geometry} material={materials.Panels} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Mid_Side_Panel_Panels_0.geometry} material={materials.Panels} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Front_Panel_Panels_0.geometry} material={materials.Panels} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.VentSteel_Handle_Panels_0.geometry} material={materials.Panels} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Front_Under_Cover_Panels_0.geometry} material={materials.Panels} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Under_Panel_Panels_0.geometry} material={materials.Panels} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Plate_with_holes_Panels_0.geometry} material={materials.Panels} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Plane_Panels_0.geometry} material={materials.Panels} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Rear_Wing_Panels_0.geometry} material={materials.Panels} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Rear_Seat_Holder_Panels_0.geometry} material={materials.Panels} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Rear_Seat_Panels_0.geometry} material={materials.Panels} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Rear_Taillight_Holder_Panels_0.geometry} material={materials.Panels} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Idk_some_under_plate_Panels_0.geometry} material={materials.Panels} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Under_plane_Panels_0.geometry} material={materials.Panels} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Exhaust_Cover_Panels_0.geometry} material={materials.Panels} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Rear_Wheel_Holder_Left_Panels_0.geometry} material={materials.Panels} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Rear_Wheel_Holder_Right_Panels_0.geometry} material={materials.Panels} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Under_Panel_Holder_Panels_0.geometry} material={materials.Panels} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Rear_Wheel_Cover_Panels_0.geometry} material={materials.Panels} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Exhaust_Cover_again_Panels_0.geometry} material={materials.Panels} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Front_Wing_Panels_0.geometry} material={materials.Panels} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Tank001_Decal_0.geometry} material={materials.Decal} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Tank002_Decal_0.geometry} material={materials.Decal} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Front_Side_Panel001_Decal_0.geometry} material={materials.Decal} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Front_Side_Panel002_Decal_0.geometry} material={materials.Decal} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Front_Side_Panel003_Decal_0.geometry} material={materials.Decal} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Front_Side_Panel004_Decal_0.geometry} material={materials.Decal} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Under_Panel001_Decal_0.geometry} material={materials.Decal} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Under_Panel002_Decal_0.geometry} material={materials.Decal} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Windshield001_Decal_0.geometry} material={materials.Decal} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Rear_Seat001_Decal_0.geometry} material={materials.Decal} position={[0, 0, -4.767]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Dashboard001_Decal_0.geometry} material={materials.Decal} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Plane003_Decal_0.geometry} material={materials.Decal} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Plane004_Decal_0.geometry} material={materials.Decal} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/kawasaki_zx-6r.glb')
