/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 letter.glb -T 
Files: letter.glb [598.9KB] > D:\Dev\Code\WS\3D_Portfolio\public\models\letter-transformed.glb [12.03KB] (98%)
Author: Arcadiax (https://sketchfab.com/arcadiax)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/letter-a3b88a6137864cafbf97423a30cb341c
Title: Letter
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Letter(props) {
  const { nodes, materials } = useGLTF('/models/letter-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube_0.geometry} material={materials.Letter} rotation={[-Math.PI / 2, 0, 0]} scale={0.429} />
    </group>
  )
}

useGLTF.preload('/models/letter-transformed.glb')
